### ISSUE TITLE
Support Annotated types

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#207]
We would like to annotate the types with `typing.Annotated` (https://docs.python.org/3/library/typing.html#typing.Annotated) to include run time value checking for the ATen lib. Annotate should only be used for attributes.

```python
@onnxscript.script()
@atenop("aten::elu")
def Elu(
    self,
    alpha: float = 1.0,
    scale: Annotated[float, Is[lambda x: x == 1.0]] = 1.0,   # Here, just need to take the float type out
    input_scale: Annotated[float, Is[lambda x: x == 1.0]] = 1.0,
):
    # del scale
    # del input_scale
    return op.Elu(self, alpha=alpha)
```

**Comment by gramalingam** [comment]
On a different note, even the use of the nested decorator `@atenop` is not supported. And may need some investigation as to what's needed there

**Comment by justinchuby** [comment]
Do you mean if the function is wrapped its unsupported, or simply having an additional decorator is unsupported?

**Comment by gramalingam** [comment]
Discussed elsewhere. In general, a decorator will have some non-trivial effect, so ignoring (during translation/conversion) may not be a good idea. But we could expose a way for users to indicate which decorators should be treated as "no effect" and ignored.
