### ISSUE TITLE
lintrunner tweaks

### ISSUE THREAD

**Issue by abock** [microsoft/onnx-script#215]
Creating a pile-on issue for problems with `lintrunner`.

- [x] The regex-based linters are wildly slow, and what's more, they result in reading and writing the same set of files many times over. Ideally all the operations should be performed in a single pass across the codebase.
	- [x] Specifically the `SPACES` (#214) linter takes many _minutes_ to complete when running against the statically generated code. This linter should just trim lines... no grep necessary.
	- [x] We can use a checker to check on .editorconfig directly https://github.com/microsoft/onnx-script/pull/227
- [x] It seems `lintrunner` does not work appropriately on Windows... this is a barrier to any dev working in Windows. WSL should not be a workaround.
	- [x] the flake8 linter does not find the .flake8 config file when running in Windows, black-isort the same. We need to figure out if that is because lintrunner doesn't set cwd properly on Windows https://github.com/justinchuby/lintrunner-adapters/pull/29
	- [x] ~We need to port all the grep linters to Windows because there is no grep~ removed all grep linters
	- [x] https://github.com/suo/lintrunner/issues/22 https://github.com/suo/lintrunner/pull/23

**Comment by justinchuby** [comment]
I think this is done.
