### ISSUE TITLE
bug: tensor types are not recognized as types

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#219]
Seen in https://github.com/microsoft/onnx-script/pull/223

1. "INT64" expects no type arguments, but 1 given  [MYPY]

	```python
	def aten_ones(size: INT64[...]) -> TensorType:
	```

2. Unexpected "..."  [MYPY]

	```python
	def aten_row_stack(tensors: TensorType[...]) -> TensorType:
	```

3. ~`INT64` does not accept a default value~ #229

	![image](https://user-images.githubusercontent.com/11205048/204673905-3b421fa4-64a8-4534-86fc-140cec19f929.png)

**Comment by abock** [comment]
The bug here was that `TensorType.__getitem__` was returning _instances_ of a new `TensorType` to carry the shape information. Instead a new type needs to be returned. Should be fixed with #228.

**Comment by abock** [comment]
@justinchuby (3) should be filed as a separate issue please.

**Comment by justinchuby** [comment]
Sure! Created #229
