### ISSUE TITLE
Implement torchscript as a graph backend

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#273]
To use onnxscript APIs for constructing graphs in pytorch, we would like to create a version that uses torchscript as the graph IR. To do this, we probably need

1. Implement an `Evaluator` that calls `g.op` to add ops and functions as nodes
2. Implement a `Tensor` that wraps around the `torch.Value`s

**Comment by gramalingam** [comment]
Just noting down a question here, hopefully our meeting later today will answer that: is the intention to have:

(i) a way of building torch IR using pythonic syntax (just like onnxscript), or
(ii) To have a deeper integration with onnxscript?

I am guessing it should be (i). In particular, do we ever expect core onnxscript to call the torch evaluator? I am assuming not.

**Comment by justinchuby** [comment]
@titaiwangms for now, an aten function can be called like

```python
from onnxscript.function_libs.torch_aten import ops

ops.core.aten_add()
```

**Comment by titaiwangms** [comment]
> @titaiwangms for now, an aten function can be called like
> 
> ```python
> from onnxscript.function_libs.torch_aten import ops
> 
> ops.core.aten_add()
> ```

ops doesn't have module core, could you check on that? I am importing 
`from onnxscript.function_libs.torch_aten.ops import core`
