### ISSUE TITLE
Torch integration plan

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#291]
1. Extract tensor to an AbstractTensor class and implement a torchscript tensor. 
2. Generate symbolic functions based on FunctionMeta https://github.com/microsoft/onnx-script/issues/271, #290 
3. #273 
4. Update OnnxFunction `__call__` to execute the ONNX function directly for this backend
5. #269 
6. Op coverage https://github.com/microsoft/onnx-script/issues/258

with which we will be able to create a torchscript graph using onnxscript APIs.

**Comment by justinchuby** [comment]
Symbolic tensors and dispatching

https://github.com/tensorflow/tensorflow/blob/v2.11.0/tensorflow/python/framework/tensor_spec.py#L130-L277
https://www.tensorflow.org/api_docs/python/tf/types/experimental/GenericFunction
https://github.com/tensorflow/tensorflow/blob/v2.11.0/tensorflow/python/types/core.py#L115-L237

**Comment by justinchuby** [comment]
TensorShape

https://www.tensorflow.org/api_docs/python/tf/TensorShape

**Comment by BowenBao** [comment]
> 3. https://github.com/microsoft/onnx-script/issues/273
> ...
> ... will be able to create a torchscript graph using onnxscript APIs

Why choosing torchscript as graph IR? Is it a temporary solution? Will we do something similar for fx IR later or how do we migrate?

**Comment by justinchuby** [comment]
> 
> Why choosing torchscript as graph IR? Is it a temporary solution? Will we do something similar for fx IR later or how do we migrate?

Because we have torch.Graph built to create onnx so I thought we can reuse it. It is a temporary solution and eventually we should migrate to a torch independent IR/class. We will use torchscript to carry pure ONNX ops. 

Migration should simply be changing the wrapper tensor that gets passed around. Generated symbolic functions and torchscript functions will be left unchanged. I will detail this in a doc.
