### ISSUE TITLE
OnnxFunction attributes with default value does not appear in IRFunction.attrs

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnx-script#317]
Repro:

```python
@script()
def aten_add(self: TReal, other: TReal, alpha: float = 1) -> TReal:
    # add.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor
    if alpha != 1:
        other = op.Mul(other, alpha)
    return op.Add(self, other)

print(aten_add.function_ir.attrs) # this should be ["alpha"]
```

cc @gramalingam @justinchuby @xiaowuhu @fatcat-z @BowenBao

**Comment by gramalingam** [comment]
Please see: https://github.com/microsoft/onnx-script/blob/main/onnxscript/irbuilder.py#L189

The IR distinguishes attributes with and without default values. It goes into function_ir.attr_protos.

It's all a bit adhoc for now. Feel free to improve it.

**Comment by titaiwangms** [comment]
@justinchuby we somehow missed it. It was so obvious lol
