### ISSUE TITLE
Strange aten_full node

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#385]
![image](https://user-images.githubusercontent.com/11205048/215242527-f37b26bd-c00e-4ee1-950b-c77cd72db20c.png)

**Comment by justinchuby** [comment]
This looks correct

**Comment by titaiwangms** [comment]
Could you elaborate more? Is this correct or wrong?

**Comment by justinchuby** [comment]
I originally thought that it's strange tensor data was empty. But it makes sense since it's supposed to be a scalar.
