### ISSUE TITLE
Turn by turn model numerical comparison (O(log(n) -> O(1))

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#393]
We can compare exported models op by op. (Eager compare results in fx by running the eager evaluator)

cc @BowenBao

**Comment by BowenBao** [comment]
Let me know when you start working on this. Feels like great candidate to integrate with diagnostics.

**Comment by titaiwangms** [comment]
> Let me know when you start working on this. Feels like great candidate to integrate with diagnostics.

Draft usage like: https://github.com/pytorch/pytorch/pull/94094

**Comment by BowenBao** [comment]
@titaiwangms Thanks, https://github.com/pytorch/pytorch/pull/94094 looks good. Echoing on @justinchuby 's comment of extracting as function.

Integration with diagnostics should then require only
1. Create a new rule in `rules.yaml`.
2. Decorate the function with `@diagnostics.decorate_call`.

I'll rebase locally after it's merged to check how it works.

**Comment by justinchuby** [comment]
@titaiwangms Great work thanks!

**Comment by titaiwangms** [comment]
1. randn_like only supports tensors, but some ops need non-tensor input, such as bool (aten_where)
2. function documentation is insufficient
3. if we set whole inputs as dynamic, how should we improve this function?

**Comment by justinchuby** [comment]
Dynamic shapes are with known ranks - maybe we can make some assumptions and create arbitrary shapes from it?

**Comment by BowenBao** [comment]
FakeTensorProp seems might have some use afterall. Used well then we have access to both dynamic and static shapes.
