### ISSUE TITLE
Make functions with string attributes trace only

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#398]
Because Equal was not defined on strings. We should split each if branch into a function. E.g. make `aten_gelu` trace only and split its body into two script functions `aten_gelue_approximate_none` and `aten_gelu_approximate_tanh`. 

#378 https://github.com/onnx/onnx/pull/4828

cc @BowenBao

**Comment by xiaowuhu** [comment]
is this a long term soluton or just for recent demo?

**Comment by justinchuby** [comment]
It’s going to be a long term solution as far as I consider

**Comment by justinchuby** [comment]
String comparison is potentially supported by opset19, which is probably too new for many use cases considering the number of functions that needs it.

**Comment by gramalingam** [comment]
Just wondering ... is using a custom-op (for string-equality) an option (as I believe the pytorch exporter uses some custom-ops)? If so, would it help, or would the split described above be sufficient?

**Comment by gramalingam** [comment]
Incidentally, I think string-equality can be simulated in existing ONNX using the [StringNormalizer](https://github.com/onnx/onnx/blob/main/docs/Operators.md#stringnormalizer) op ... but it seems a bit convoluted to do this. But mentioning it, just in case.

**Comment by justinchuby** [comment]
> Just wondering ... is using a custom-op (for string-equality) an option (as I believe the pytorch exporter uses some custom-ops)? If so, would it help, or would the split described above be sufficient?

The split would be sufficient for now, but support in Equal is certainly desired. I don't think we have custom ops to use?

> Incidentally, I think string-equality can be simulated in existing ONNX using the [StringNormalizer](https://github.com/onnx/onnx/blob/main/docs/Operators.md?rgh-link-date=2023-02-01T20%3A52%3A22Z#stringnormalizer) op ... but it seems a bit convoluted to do this. But mentioning it, just in case.

Could you share an example of how we can use it?

**Comment by justinchuby** [comment]
Fixed by #402
