### ISSUE TITLE
Make functions with if and dtype attributes trace_only

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#419]
According to Rama, if branches needs to produce the same type and this conflicts with some logic we have in the atenlib

**Comment by BowenBao** [comment]
:( More and more `trace_only` ops... Is there a way to automate the decision if `trace_only` should be applied?

**Comment by justinchuby** [comment]
I think it's still good if we make a conscious choice. I am going to create a guide #388 for it.
