### ISSUE TITLE
Enable merge queue

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#433]
It would be nice to enable merge queues similar to https://github.com/onnx/onnx/issues/4884. 

https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

@abock @gramalingam

**Comment by jcwchen** [comment]
+1 Although onnx repo now bumped into DCO issue, it looks good to enable merge queue in this repo, because there is no required DCO. Here is the example PR to enable merge queue in pipelines: https://github.com/onnx/onnx/pull/4890.

**Comment by justinchuby** [comment]
idk if the microsoft cla bot would see the same issue?

**Comment by justinchuby** [comment]
Probably later
