### ISSUE TITLE
Unpack prim::ListConstruct if it's not depreacated in fx

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnx-script#481]
Not sure if List::Construct is deprecated, and if it's not, ~~maybe we should unpack list in `_wrap_torch_value_to_tensor`~~, how should we unpack it in the ops... I think it's deprecated though. Feel like it's a JIT thing.

cc @justinchuby @BowenBao

**Comment by BowenBao** [comment]
Definitely not part of the prim core nor aten core. Are you observing this from some model?

Yet I'm not surprised if there exists a new semantically equivalent operator by another name in fx..

**Comment by titaiwangms** [comment]
Not yet, they are possibly using like python list to contain Tensors, but just in case, I created this issue.

**Comment by titaiwangms** [comment]
Reorganize the findings:

1. Background: TorchScriptTensor wrapper happens in `graph_building.add_input`, ever since then, the class was used to replace fx.Node/torch.Value across whole exporting by `fx_name_to_onnxscipt_value` dictionary, and output of a function can only be TorchScriptTensor. And graph_building use `isinstance(value, TorchScriptTensor)` to determin a value is constant input or not.

2. Let's say we need a dynamic size (2nd input) in onnx::Expand node, which is generated depending on multiple inputs shapes/dims. fx.graph would wrap them with python List like: [size0, size1. size2], and the name would connect to TorchScriptTensor through `fx_name_to_onnxscipt_value`, but in order to make it a valid input, the List is needed to be wrapped or processed to acceptable TorchScriptTensor to the node.

3. TL;DR fx.graph uses list of tensors to replace List::Construct
