### ISSUE TITLE
CI Failure: py310-experimental

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnx-script#488]
https://github.com/microsoft/onnx-script/actions/runs/4306802048/jobs/7511076762
```
SUBFAIL onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py::TestOutputConsistencyCPU::test_output_match_max_reduction_with_dim_cpu_float32 - RuntimeError: Unable to create onnxruntime InferenceSession for executing .OptionalHasElement op with onnx model
<
   ir_version: 8,
   opset_import: ["" : 18]
>
node_graph (int64 input0) => (bool output0) {
   output0 = OptionalHasElement (input0)
}
=========== 55 failed, 1107 passed, 485 skipped, 6 xfailed in 50.34s ===========
nox > Command pytest onnxscript -v --cov=onnxscript --cov-report=xml --cov-append --cov-branch -n=auto failed with exit code 1
nox > Session test_onnx_func_expe failed.
```

cc @justinchuby @titaiwangms

**Comment by titaiwangms** [comment]
I think we need to merge these branch with latest ort:
https://github.com/microsoft/onnx-script/blob/5ba4fc7d38d3ff0a6eda925a95d6bffe3b0ea5c6/requirements-dev.txt#L4-L7

@liqunfu Could you update the experimental branch?

**Comment by liqunfu** [comment]
I will push this BR merged: https://github.com/onnx/onnx/pull/4911
After we can use onnx main branch instead.

**Comment by liqunfu** [comment]
merging and building the experimental branch... stay tuned

**Comment by liqunfu** [comment]
@titaiwangms talked to @BowenBao - this is not a blocking issue. I will not work on the experimental branch. Instead I will push and merge https://github.com/onnx/onnx/pull/4911 which allows to remove dependency on the experimental branch.
