### ISSUE TITLE
[regression][atenlib] #459 broke pytorch gpt2 export

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnx-script#489]
Discovered by https://github.com/pytorch/pytorch/pull/95676, https://github.com/pytorch/pytorch/actions/runs/4306983689/jobs/7511796215. Introduced by #459

### TL;DR 
It seems `axes` is considered `onnxAttributes`, but got type `TorchScriptTensor`.

Is it because the type annotation for `axes` is wrong?
https://github.com/microsoft/onnx-script/blob/e66ca88c9b0beb6e45545d4c60d96c65e70c9db8/onnxscript/function_libs/torch_aten/ops/core.py#L3995

Why is this not caught in unittest?

### Using sarif to pinpoint the error

Checking the generated diagnostic `test_report_test_gpt2_tiny.sarif`, with WARNING + ERROR filter
![image](https://user-images.githubusercontent.com/9376104/222282385-f038afca-6d0d-42a6-a4bf-8dbb7080b65d.png)

Viewing `_add_torchscript_op_call` as part of the analysis step, we could observe (in json unfortunately since sarif extension does not visualize step detail info) 

```
           "state":{
            "name":"onnxscript.atenlib::_aten_native_layer_norm_onnx: <class 'str'>",
            "onnxInputs":"[TorchScriptTensor(None), TorchScriptTensor(None), TorchScriptTensor(None)]: <class 'list'>",
            "onnxAttributes":"OrderedDict([('axes', TorchScriptTensor(None)), ('eps', 1e-05)]): <class 'collections.OrderedDict'>",
            "nOutputs":"3: <class 'int'>"
           }
```
It shows `axes` is considered `onnxAttributes`, but got type `TorchScriptTensor`.

**Comment by abock** [comment]
@xiaowuhu would you please take a look? Thanks!

**Comment by titaiwangms** [comment]
I think the root cause is this: https://github.com/microsoft/onnx-script/commit/690ed5db3bbcec508604fad19f74ebd51378c9a3#r102668770

**Comment by wschin** [comment]
Op level test is not enough to protect end-to-end exporting. Is there a plan to test against all HF models in somewhere?

**Comment by BowenBao** [comment]
@justinchuby I'm curious if it is possible to cover `TorchScriptGraph` with `ops_correctness_test`?

**Comment by BowenBao** [comment]
> We can construct but not execute. I think it's still useful?

Yea should be enough to catch errors like this, which is raised from graph building. But why can't we execute though? I thought we can `to_model_proto` then run through onnx backend?

**Comment by justinchuby** [comment]
actually you are right. We can run it the same way we run the O(1) tests

**Comment by justinchuby** [comment]
Done
