### ISSUE TITLE
Does it possible to generate onnx graph with symbolic shape input?

### ISSUE THREAD

**Issue by wejoncy** [microsoft/onnx-script#561]
Hi.

I am wondering can we support generate arbitrary graph with a piece of script function?

I don't have a concret shape and input tensor when I ran onnx-script, so I can't build a input-array with numpy and running through the script as the example in DOC.

So my question is:
- How Can I build a input tensor with symbolic shape, say ["I1","I2","I3",....]?
- How can I get the graph from corresponding python-code?

My current solution is to build a  textual representation of onnx IR, and then leverage [onnx.parser.parse_graph](https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#onnx-parser) to generate onnx graph.

Onnx -script will help a lot if we can make it.

**Comment by gramalingam** [comment]
Yes, you can do it in onnx-script. The execution using numpy arrays you mentions (called eager-mode) it meant mostly to run/execute the function for testing/debugging purposes. 

Eg., see [the square_loss example](https://github.com/microsoft/onnx-script/blob/main/docs/examples/02_plot_square_loss.py)

**Comment by wejoncy** [comment]
> * or with symbolic shape, say ["I1","I2","I3",....]?
> * How can I get the graph from corresponding python-code?
> 
> My current solution is to build a t

Thanks for your quick responce.
That's what I want.

Thanks.
