### ISSUE TITLE
mypy complains ONNX Script is not PEP 561 compliant

### ISSUE THREAD

**Issue by abock** [microsoft/onnx-script#572]
It seems we need to explicitly declare ONNX Script as [PEP 561](https://peps.python.org/pep-0561/) compliant in order for mypy to follow into it from an external package (e.g. usage inside PyTorch).

In PyTorch we see the [following error](
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker):

```
  Error (MYPY) [import]
    Skipping analyzing "onnxscript": module is installed, but missing library
    stubs or py.typed marker

        198  |        #   supported opset version Y
        199  |        # - etc.
        200  |        import onnx
    >>> 201  |        import onnxscript
        202  |
        203  |        assert onnx.defs.onnx_opset_version() >= opset_version
        204  |        assert isinstance(
```

ONNX Script is installed, but because mypy cannot determine if it's meant to be typed, it does not descend into it, resulting in `onnxscript` being treated as `Any`.

**Comment by shubhambhokare1** [comment]
#579 Should fix this.
